method: skill
data:
  dataset: skill
  train_split: train
  val_split: val
  test_split: test
  dim: 3
  padding: 0.0
  type: geom
model:
  n_hands: 1
  action_dim: 26
  state_dim: 128
  latent_dim: 128

  state_encoder_kwargs:
    ckpt_file: None


training:
  out_dir: out/default
  batch_size: 64
  pos_weight: 5
  print_every: 200
  visualize_every: 1000
  visualize_total: 15
  checkpoint_every: 1000
  validate_every: 2000
  backup_every: 100000
  eval_sample: false
  model_selection_metric: loss
  model_selection_mode: minimize
  n_workers: 4
  n_workers_val: 4
test:
  threshold: 0.5
  eval_mesh: true
  eval_pointcloud: true
  remove_wall: false
  model_file: model_best.pt

generation:
  batch_size: 100000
  refinement_step: 0
  vis_n_outputs: 30
  generate_mesh: true
  generate_pointcloud: true
  generation_dir: generation
  use_sampling: false
  resolution_0: 32
  upsampling_steps: 3
  simplify_nfaces: null
  copy_groundtruth: false
  copy_input: true
  latent_number: 4
  latent_H: 8
  latent_W: 8
  latent_ny: 2
  latent_nx: 2
  latent_repeat: true
  sliding_window: False # added for crop generation
